// Generated by gencpp from file ultralytics_ros/DetectionArray.msg
// DO NOT EDIT!


#ifndef ULTRALYTICS_ROS_MESSAGE_DETECTIONARRAY_H
#define ULTRALYTICS_ROS_MESSAGE_DETECTIONARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <ultralytics_ros/Detection.h>

namespace ultralytics_ros
{
template <class ContainerAllocator>
struct DetectionArray_
{
  typedef DetectionArray_<ContainerAllocator> Type;

  DetectionArray_()
    : header()
    , detections()  {
    }
  DetectionArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , detections(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::ultralytics_ros::Detection_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::ultralytics_ros::Detection_<ContainerAllocator> >> _detections_type;
  _detections_type detections;





  typedef boost::shared_ptr< ::ultralytics_ros::DetectionArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ultralytics_ros::DetectionArray_<ContainerAllocator> const> ConstPtr;

}; // struct DetectionArray_

typedef ::ultralytics_ros::DetectionArray_<std::allocator<void> > DetectionArray;

typedef boost::shared_ptr< ::ultralytics_ros::DetectionArray > DetectionArrayPtr;
typedef boost::shared_ptr< ::ultralytics_ros::DetectionArray const> DetectionArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ultralytics_ros::DetectionArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ultralytics_ros::DetectionArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ultralytics_ros::DetectionArray_<ContainerAllocator1> & lhs, const ::ultralytics_ros::DetectionArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.detections == rhs.detections;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ultralytics_ros::DetectionArray_<ContainerAllocator1> & lhs, const ::ultralytics_ros::DetectionArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ultralytics_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ultralytics_ros::DetectionArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ultralytics_ros::DetectionArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ultralytics_ros::DetectionArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ultralytics_ros::DetectionArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ultralytics_ros::DetectionArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ultralytics_ros::DetectionArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ultralytics_ros::DetectionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a083f705d50596d301a4f958a078d859";
  }

  static const char* value(const ::ultralytics_ros::DetectionArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa083f705d50596d3ULL;
  static const uint64_t static_value2 = 0x01a4f958a078d859ULL;
};

template<class ContainerAllocator>
struct DataType< ::ultralytics_ros::DetectionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ultralytics_ros/DetectionArray";
  }

  static const char* value(const ::ultralytics_ros::DetectionArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ultralytics_ros::DetectionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# represents all YOLOv8 detections in one frame\n"
"\n"
"std_msgs/Header header\n"
"ultralytics_ros/Detection[] detections\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: ultralytics_ros/Detection\n"
"# defines a YOLOv8 detection result\n"
"\n"
"# class probability\n"
"int32 class_id\n"
"string class_name\n"
"float64 score\n"
"\n"
"# ID for tracking\n"
"string id\n"
"\n"
"# 2D bounding box surrounding the object in pixels\n"
"ultralytics_ros/BoundingBox2D bbox\n"
"\n"
"# 3D bounding box surrounding the object in meters\n"
"ultralytics_ros/BoundingBox3D bbox3d\n"
"\n"
"# segmentation mask of the detected object\n"
"# it is only the boundary of the segmented object\n"
"ultralytics_ros/Mask mask\n"
"\n"
"# keypoints for human pose estimation\n"
"ultralytics_ros/KeyPoint2DArray keypoints\n"
"\n"
"# keypoints for human pose estimation\n"
"ultralytics_ros/KeyPoint3DArray keypoints3d\n"
"================================================================================\n"
"MSG: ultralytics_ros/BoundingBox2D\n"
"# 2D position and orientation of the bounding box center\n"
"ultralytics_ros/Pose2D center\n"
"\n"
"# total size of the bounding box, in pixels, surrounding the object's center\n"
"ultralytics_ros/Vector2 size\n"
"================================================================================\n"
"MSG: ultralytics_ros/Pose2D\n"
"# 2D position in pixel coordinates\n"
"\n"
"ultralytics_ros/Point2D position\n"
"float64 theta\n"
"================================================================================\n"
"MSG: ultralytics_ros/Point2D\n"
"# 2D point in pixel coordinates\n"
"\n"
"float64 x\n"
"float64 y\n"
"================================================================================\n"
"MSG: ultralytics_ros/Vector2\n"
"# 2D size in pixel\n"
"\n"
"float64 x\n"
"float64 y\n"
"================================================================================\n"
"MSG: ultralytics_ros/BoundingBox3D\n"
"# 3D position and orientation of the bounding box center\n"
"geometry_msgs/Pose center\n"
"\n"
"# total size of the bounding box, in meters, surrounding the object's center\n"
"geometry_msgs/Vector3 size\n"
"\n"
"# frame reference\n"
"string frame_id\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: ultralytics_ros/Mask\n"
"# segmentation mask for one instance\n"
"\n"
"# size of the original image\n"
"int32 height\n"
"int32 width\n"
"\n"
"# mask data represeted by the points of the border of the mask\n"
"ultralytics_ros/Point2D[] data\n"
"================================================================================\n"
"MSG: ultralytics_ros/KeyPoint2DArray\n"
"# represents all the keypoints for human pose estimation\n"
"\n"
"ultralytics_ros/KeyPoint2D[] data\n"
"================================================================================\n"
"MSG: ultralytics_ros/KeyPoint2D\n"
"# one keypoint for human pose estimation\n"
"\n"
"# id of the keypoint\n"
"int32 id\n"
"\n"
"# 2D point in pixels\n"
"ultralytics_ros/Point2D point\n"
"\n"
"# conf of the keypoint\n"
"float64 score\n"
"================================================================================\n"
"MSG: ultralytics_ros/KeyPoint3DArray\n"
"# represents all the keypoints for human pose estimation in meters\n"
"\n"
"ultralytics_ros/KeyPoint3D[] data\n"
"\n"
"# frame reference\n"
"string frame_id\n"
"================================================================================\n"
"MSG: ultralytics_ros/KeyPoint3D\n"
"# one keypoint for human pose estimation\n"
"\n"
"# id of the keypoint\n"
"int32 id\n"
"\n"
"# 3D point in meters\n"
"geometry_msgs/Point point\n"
"\n"
"# conf of the keypoint\n"
"float64 score\n"
;
  }

  static const char* value(const ::ultralytics_ros::DetectionArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ultralytics_ros::DetectionArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.detections);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectionArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ultralytics_ros::DetectionArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ultralytics_ros::DetectionArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "detections[]" << std::endl;
    for (size_t i = 0; i < v.detections.size(); ++i)
    {
      s << indent << "  detections[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ultralytics_ros::Detection_<ContainerAllocator> >::stream(s, indent + "    ", v.detections[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ULTRALYTICS_ROS_MESSAGE_DETECTIONARRAY_H
