// Generated by gencpp from file ultralytics_ros/KeyPoint2DArray.msg
// DO NOT EDIT!


#ifndef ULTRALYTICS_ROS_MESSAGE_KEYPOINT2DARRAY_H
#define ULTRALYTICS_ROS_MESSAGE_KEYPOINT2DARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ultralytics_ros/KeyPoint2D.h>

namespace ultralytics_ros
{
template <class ContainerAllocator>
struct KeyPoint2DArray_
{
  typedef KeyPoint2DArray_<ContainerAllocator> Type;

  KeyPoint2DArray_()
    : data()  {
    }
  KeyPoint2DArray_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::ultralytics_ros::KeyPoint2D_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::ultralytics_ros::KeyPoint2D_<ContainerAllocator> >> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::ultralytics_ros::KeyPoint2DArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ultralytics_ros::KeyPoint2DArray_<ContainerAllocator> const> ConstPtr;

}; // struct KeyPoint2DArray_

typedef ::ultralytics_ros::KeyPoint2DArray_<std::allocator<void> > KeyPoint2DArray;

typedef boost::shared_ptr< ::ultralytics_ros::KeyPoint2DArray > KeyPoint2DArrayPtr;
typedef boost::shared_ptr< ::ultralytics_ros::KeyPoint2DArray const> KeyPoint2DArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ultralytics_ros::KeyPoint2DArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ultralytics_ros::KeyPoint2DArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ultralytics_ros::KeyPoint2DArray_<ContainerAllocator1> & lhs, const ::ultralytics_ros::KeyPoint2DArray_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ultralytics_ros::KeyPoint2DArray_<ContainerAllocator1> & lhs, const ::ultralytics_ros::KeyPoint2DArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ultralytics_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ultralytics_ros::KeyPoint2DArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ultralytics_ros::KeyPoint2DArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ultralytics_ros::KeyPoint2DArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ultralytics_ros::KeyPoint2DArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ultralytics_ros::KeyPoint2DArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ultralytics_ros::KeyPoint2DArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ultralytics_ros::KeyPoint2DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c319c71fb3a0d705740c7312436635df";
  }

  static const char* value(const ::ultralytics_ros::KeyPoint2DArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc319c71fb3a0d705ULL;
  static const uint64_t static_value2 = 0x740c7312436635dfULL;
};

template<class ContainerAllocator>
struct DataType< ::ultralytics_ros::KeyPoint2DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ultralytics_ros/KeyPoint2DArray";
  }

  static const char* value(const ::ultralytics_ros::KeyPoint2DArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ultralytics_ros::KeyPoint2DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# represents all the keypoints for human pose estimation\n"
"\n"
"ultralytics_ros/KeyPoint2D[] data\n"
"================================================================================\n"
"MSG: ultralytics_ros/KeyPoint2D\n"
"# one keypoint for human pose estimation\n"
"\n"
"# id of the keypoint\n"
"int32 id\n"
"\n"
"# 2D point in pixels\n"
"ultralytics_ros/Point2D point\n"
"\n"
"# conf of the keypoint\n"
"float64 score\n"
"================================================================================\n"
"MSG: ultralytics_ros/Point2D\n"
"# 2D point in pixel coordinates\n"
"\n"
"float64 x\n"
"float64 y\n"
;
  }

  static const char* value(const ::ultralytics_ros::KeyPoint2DArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ultralytics_ros::KeyPoint2DArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct KeyPoint2DArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ultralytics_ros::KeyPoint2DArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ultralytics_ros::KeyPoint2DArray_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ultralytics_ros::KeyPoint2D_<ContainerAllocator> >::stream(s, indent + "    ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ULTRALYTICS_ROS_MESSAGE_KEYPOINT2DARRAY_H
