// Generated by gencpp from file ultralytics_ros/Mask.msg
// DO NOT EDIT!


#ifndef ULTRALYTICS_ROS_MESSAGE_MASK_H
#define ULTRALYTICS_ROS_MESSAGE_MASK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ultralytics_ros/Point2D.h>

namespace ultralytics_ros
{
template <class ContainerAllocator>
struct Mask_
{
  typedef Mask_<ContainerAllocator> Type;

  Mask_()
    : height(0)
    , width(0)
    , data()  {
    }
  Mask_(const ContainerAllocator& _alloc)
    : height(0)
    , width(0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _height_type;
  _height_type height;

   typedef int32_t _width_type;
  _width_type width;

   typedef std::vector< ::ultralytics_ros::Point2D_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::ultralytics_ros::Point2D_<ContainerAllocator> >> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::ultralytics_ros::Mask_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ultralytics_ros::Mask_<ContainerAllocator> const> ConstPtr;

}; // struct Mask_

typedef ::ultralytics_ros::Mask_<std::allocator<void> > Mask;

typedef boost::shared_ptr< ::ultralytics_ros::Mask > MaskPtr;
typedef boost::shared_ptr< ::ultralytics_ros::Mask const> MaskConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ultralytics_ros::Mask_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ultralytics_ros::Mask_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ultralytics_ros::Mask_<ContainerAllocator1> & lhs, const ::ultralytics_ros::Mask_<ContainerAllocator2> & rhs)
{
  return lhs.height == rhs.height &&
    lhs.width == rhs.width &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ultralytics_ros::Mask_<ContainerAllocator1> & lhs, const ::ultralytics_ros::Mask_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ultralytics_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ultralytics_ros::Mask_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ultralytics_ros::Mask_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ultralytics_ros::Mask_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ultralytics_ros::Mask_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ultralytics_ros::Mask_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ultralytics_ros::Mask_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ultralytics_ros::Mask_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c0265cc03cecfba2043d52503f335bb0";
  }

  static const char* value(const ::ultralytics_ros::Mask_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc0265cc03cecfba2ULL;
  static const uint64_t static_value2 = 0x043d52503f335bb0ULL;
};

template<class ContainerAllocator>
struct DataType< ::ultralytics_ros::Mask_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ultralytics_ros/Mask";
  }

  static const char* value(const ::ultralytics_ros::Mask_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ultralytics_ros::Mask_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# segmentation mask for one instance\n"
"\n"
"# size of the original image\n"
"int32 height\n"
"int32 width\n"
"\n"
"# mask data represeted by the points of the border of the mask\n"
"ultralytics_ros/Point2D[] data\n"
"================================================================================\n"
"MSG: ultralytics_ros/Point2D\n"
"# 2D point in pixel coordinates\n"
"\n"
"float64 x\n"
"float64 y\n"
;
  }

  static const char* value(const ::ultralytics_ros::Mask_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ultralytics_ros::Mask_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.height);
      stream.next(m.width);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Mask_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ultralytics_ros::Mask_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ultralytics_ros::Mask_<ContainerAllocator>& v)
  {
    s << indent << "height: ";
    Printer<int32_t>::stream(s, indent + "  ", v.height);
    s << indent << "width: ";
    Printer<int32_t>::stream(s, indent + "  ", v.width);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ultralytics_ros::Point2D_<ContainerAllocator> >::stream(s, indent + "    ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ULTRALYTICS_ROS_MESSAGE_MASK_H
